dbfilename redis_queue.rdb
dir /home/sjayp/Cooperative_manager/coop-bench/config/pids
pidfile /home/sjayp/Cooperative_manager/coop-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/sjayp/Cooperative_manager/coop-bench/config/redis_queue.acl
